USE test;
DELETE FROM `organizers_teams` WHERE 1=1;
DELETE FROM `tournaments` WHERE 1=1;
DELETE FROM `organizers` WHERE 1=1;
DELETE FROM `teams` WHERE 1=1;
DELETE FROM `users` WHERE 1=1;
INSERT INTO `users` VALUES(1);
INSERT INTO `users` VALUES(2);
INSERT INTO `organizers` VALUES(1, 'Ignis', 1, 100, 'Best place to play!');
INSERT INTO `organizers` VALUES(2, 'VGL', 2, 1000, 'Second Best place to play!');
INSERT INTO `teams` VALUES(1, 'FuRy', 1, 'Andrew is a god');
INSERT INTO `teams` VALUES(2, 'Artemis', 2, 'Not your average expieriance');
INSERT INTO `teams` VALUES(3, 'Faze', 2, 'Olof is a criminal');
INSERT INTO `teams` VALUES(4, 'Outer Heavan', 1, '... wtf');
INSERT INTO `tournaments` VALUES(1, 1, 'New Year', 2, 8, '2018-1-1 8:00:00', '2018-1-20', 100000, 'New year special');
INSERT INTO `tournaments` (`id`, `organizer_id`, `name`, `type`, `size`, `start_date`, `entry_fee`, `description`) VALUES(2, 1, 'Christmas', 1, 4, '2018-12-25 12:30:00', 500, 'Christmas special');
INSERT INTO `organizers_teams` VALUES(1, 1, 1, 0);
INSERT INTO `organizers_teams` VALUES(2, 1, 2, 0);
INSERT INTO `organizers_teams` VALUES(3, 1, 3, 0);
INSERT INTO `organizers_teams` VALUES(4, 1, 4, 0);
INSERT INTO `organizers_teams` VALUES(5, 2, 1, 0);
INSERT INTO `organizers_teams` VALUES(6, 2, 2, 1);